### ISSUE TITLE
Special characters, etc. in cell collective variable names

### ISSUE THREAD

**Issue by jcrozum** [jcrozum/cubewalkers#15]
I scanned through all cell collective models to make sure they simulate. I'm using the `load_all_cell_collective_models` function from [here](https://github.com/rionbr/CANA/blob/master/cana/datasets/bio.py) as well as Felipe's `net_alg_rule` function (BTW, please rename this to something more descriptive). Eventually, everything simulated using `threads_per_block=(16,16)`, `W=100`, `T=10`, and `averages_only=True`. It takes only a minute or two (generating network 31 takes most of the time). Here are the problems I found:

- Network 12 has `+` and `-` as part of some variable names.
- Network 47 has variable names with `/` and with `(`/`)`.
- Network 56 has a variable that starts with `3`.

I was able to get everything to simulate by adding the following to the end of `net_alg_rule`:
```python
alg_rule = re.sub("-", "_", alg_rule)
alg_rule = re.sub("\+", "_plus", alg_rule)
alg_rule = re.sub("/", "_", alg_rule)
alg_rule = re.sub("G\(i_o\)", "G_io", alg_rule)
alg_rule = re.sub("3_", "three_", alg_rule)
alg_rule = re.sub("\(P\)", "_P_", alg_rule)
```
(and of course you need to add `import re` to the top as well).

While this works, it is a bit too ad-hoc, especially the last three lines. Let's try to come up with better replacements so this can be generalized. Perhaps the more general version could go in the parser function.

**Comment by fcphysics** [comment]
Pull request #18 made with those editions implemented. There might be other ones, so we might want to leave this open?
