### ISSUE TITLE
Additional PBN schemes

### ISSUE THREAD

**Issue by jcrozum** [jcrozum/cubewalkers#2]
Currently, only synchronous PBNs are implemented. It should be straightforward to generalize to the other updating schemes.

I have already implemented two versions of synchronous PBN support: one in which each node for each walker gets an independent random value from [0,1], and another where each walker uses the same value for all nodes.

These should be extended to the asynchronous and asynchronous set update schemes.

**Comment by troonmel** [comment]
I'm trying to speed up the generation of PBN update masks. I tested few methods, and some seem to be fast in low numbers of W and T, but scale poorly, and some are the other way round.

What are the reasonable range of N, W, T that I should test the update masks on?
I'm thinking T should depend on the update scheme and the number of nodes. T=100 may be more than enough for synchronous update, but won't be enough for asynchronous update with N=100.

**Comment by jcrozum** [comment]
I'd guess that the runtime is something like
$C_0 + (C_1 + C_2\times N\times W)\times T$,
where $C_0 \approx 1sec$, and $C_1$ and $C_2$ are pretty small compared to $C_0$, but $C_2$ depends heavily on the efficiency of generating the update mask.

Does that seem consistent with what you're seeing? If we can get a good idea of what the scaling looks like, we can pick test numbers in a more principled way.

Anyway, for a "reasonably heavy" load, N=100, T=100, W=1000 is probably pretty good to start if you just want some numbers to get a rough idea of how different methods compare. If you're consistently getting less than about 2 seconds, start by increasing T so that things average out more. (By the way, how are you generating the networks with the specified N value?)

We can discuss how to do more rigorous benchmarks in a separate issue if you want, but I think for now a 'quick and dirty' approach is good enough.

**Comment by troonmel** [comment]
I think your equation does capture trend of the runtimes.
I've been using load like N=100, W=T=10000,  so I guess this was a bit of an overkill.
Right now I'm just testing the generation of update masks only, so I don't have to generate networks.

**Comment by jcrozum** [comment]
I see, so T here is just how many masks to generate I guess. In my (very limited) testing, the mask generation is the slowest part, so I think that's fine.

And yes, N=100, W=T=10000 is probably overkill at this stage. You just want it long enough that the initial overhead is much less than the total runtime.

**Comment by troonmel** [comment]
I tried writing the asynchronous_set_PBN using the putmask(). It got much slower.

original: ~2s for N=100, W=1000, T=10000
    z = cp.random.random((n, w), dtype=cp.float32)
    z = cp.subtract(z, 0.5)
    z = cp.absolute(z) + z

new: ~7s for N=100, W=1000, T=10000
    z = cp.random.random((n, w), dtype=cp.float32)
    z = cp.subtract(z, 0.5) * 2
    cp.putmask(z, z<0, 0)

My guess is that putmask is very slow.

**Comment by jcrozum** [comment]
How about this for faster asynchronous mask generation:

```python
n=4 # just for a quick test
w=5

x=cp.ones((1,w)) # could make cp.random.random(size=(1,w)) for pbn
z=cp.concatenate((x,cp.zeros((n-1,w))))
cp.apply_along_axis(cp.random.permutation,arr=z,axis=0) # return this
```

**Comment by troonmel** [comment]
apply_along_axis is exactly what I wanted. Unfortunately it is much slower.
N=100, W=1000, T=100 took ~42 seconds, so T=10000 will roughly take 4200 seconds.

**Comment by troonmel** [comment]
The current best for asynchronous mask generation is ~6 seconds

`
    updates = 0.0
    while updates != w:
        z = cp.random.random((n,w), dtype=cp.float32)
        z = z - cp.max(z, axis=0)
        z = 1 + cp.sign(z)
        updates = cp.sum(z)
`

**Comment by jcrozum** [comment]
I've been trying to come up with a faster way, and I can't seem to do much better than what you already have. I did manage to slightly improve what you came up with, for about a 10% speedup in my tests:

```python
def test(t: int, n: int, w: int, a: cp.ndarray) -> cp.ndarray:
    z = cp.random.random((n,w), dtype=cp.float32)
    mz = cp.equal(z,cp.max(z, axis=0))
    
    while cp.sum(mz) != w:
        z = cp.random.random((n,w), dtype=cp.float32)
        mz = cp.equal(z,cp.max(z, axis=0))    
        
    return mz.astype(cp.float32)
```
By the way, I'm not sure what you're using for benchmarks, but we should probably use the `cupyx.benchmark` function, described here: https://docs.cupy.dev/en/stable/user_guide/performance.html

**Comment by troonmel** [comment]
Here's the current standing.

N=100, W=1000, T=10000
synch				CPU:   32.473 us   +/-12.674 us	GPU:   71.285 us   +/-18.625 us
asynch				CPU:  473.707 us   +/-52.169 us	GPU:  522.041 us   +/-54.565 us
asynch_set			CPU:   80.123 us   +/-18.560 us	GPU:  180.820 us   +/-22.140 us
synch_PBN			CPU:   75.721 us   +/-19.542 us	GPU:  176.279 us   +/-23.613 us
synch_PBN_dep		CPU:  119.367 us   +/-35.271 us	GPU:  209.978 us   +/-38.554 us
asynch_PBN			CPU:  575.372 us   +/-73.255 us	GPU:  657.716 us   +/-76.062 us
asynch_set_PBN		CPU:  102.213 us   +/-18.788 us	GPU:  251.429 us   +/-23.686 us
asynch_set_PBN_dep	CPU:  157.553 us   +/-29.224 us	GPU:  273.877 us   +/-32.512 us
